-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["Dude_Monster_Run_6-0"] = {
                    
                    
                    {
                    pe_fixture_id = "dude-monster-run6-0", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -2, 13  ,  -6, 8  ,  -6, 1  ,  6, 9  ,  5, 14  }
                    } ,
                    {
                    pe_fixture_id = "dude-monster-run6-0", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -6, 8  ,  -2, 13  ,  -3, 15  ,  -7, 15  ,  -9, 13  ,  -9, 10  }
                    } ,
                    {
                    pe_fixture_id = "dude-monster-run6-0", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -7, -4  ,  -1, -10  ,  6, -9  ,  10, -4  ,  8, 3  ,  6, 9  ,  -6, 1  }
                    } ,
                    {
                    pe_fixture_id = "dude-monster-run6-0", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   6, 9  ,  8, 3  ,  8, 7  }
                    } ,
                    {
                    pe_fixture_id = "dude-monster-run6-0", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   8, 3  ,  10, -4  ,  10, 1  }
                    }
		}
		, 
		["Dude_Monster_Run_6-1"] = {
                    
                    
                    {
                    pe_fixture_id = "dude-monster-run6-1", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -8, 6  ,  -6, 4  ,  6, 10  ,  5, 15  ,  0, 13  }
                    } ,
                    {
                    pe_fixture_id = "dude-monster-run6-1", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -6, 4  ,  -6, -6  ,  -1, -10  ,  6, -9  ,  10, -4  ,  10, 1  ,  8, 3  }
                    } ,
                    {
                    pe_fixture_id = "dude-monster-run6-1", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -8, 13  ,  -8, 6  ,  0, 13  ,  -6, 15  }
                    } ,
                    {
                    pe_fixture_id = "dude-monster-run6-1", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   6, 10  ,  -6, 4  ,  8, 3  ,  8, 9  }
                    } ,
                    {
                    pe_fixture_id = "dude-monster-run6-1", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   5, 15  ,  0, 15  ,  0, 13  }
                    }
		}
		, 
		["Dude_Monster_Run_6-2"] = {
                    
                    
                    {
                    pe_fixture_id = "dude-monster-run6-2", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   5, 12  ,  -6, 5  ,  -6, -4  ,  -1, -8  ,  8, 5  ,  9, 10  }
                    } ,
                    {
                    pe_fixture_id = "dude-monster-run6-2", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   6, 16  ,  -7, 16  ,  -9, 7  ,  -6, 5  ,  5, 12  }
                    } ,
                    {
                    pe_fixture_id = "dude-monster-run6-2", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -1, -8  ,  4, -8  ,  10, -2  ,  10, 3  ,  8, 5  }
                    }
		}
		, 
		["Dude_Monster_Run_6-3"] = {
                    
                    
                    {
                    pe_fixture_id = "dude-monster-run6-3", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   5, 9  ,  -5, 9  ,  -7, -4  ,  -3, -9  ,  4, -10  ,  8, 3  ,  9, 8  }
                    } ,
                    {
                    pe_fixture_id = "dude-monster-run6-3", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -5, 9  ,  5, 9  ,  5, 12  ,  2, 15  ,  -4, 14  }
                    } ,
                    {
                    pe_fixture_id = "dude-monster-run6-3", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -9, 5  ,  -6, 3  ,  -5, 9  ,  -9, 8  }
                    } ,
                    {
                    pe_fixture_id = "dude-monster-run6-3", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   4, -10  ,  10, -4  ,  10, 1  ,  8, 3  }
                    }
		}
		, 
		["Dude_Monster_Run_6-4"] = {
                    
                    
                    {
                    pe_fixture_id = "dude-monster-run6-4", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -4, 10  ,  5, 10  ,  5, 12  ,  2, 15  ,  -3, 15  }
                    } ,
                    {
                    pe_fixture_id = "dude-monster-run6-4", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -8, 5  ,  -6, 3  ,  8, 3  ,  5, 10  ,  -4, 10  ,  -8, 9  }
                    } ,
                    {
                    pe_fixture_id = "dude-monster-run6-4", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   5, 10  ,  8, 3  ,  9, 9  }
                    } ,
                    {
                    pe_fixture_id = "dude-monster-run6-4", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -6, 3  ,  -7, -4  ,  -3, -9  ,  4, -10  ,  10, -4  ,  10, 1  ,  8, 3  }
                    }
		}
		, 
		["Dude_Monster_Run_6-5"] = {
                    
                    
                    {
                    pe_fixture_id = "dude-monster-run6-5", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -8, 8  ,  -6, 6  ,  8, 5  ,  8, 11  ,  -5, 12  ,  -8, 11  }
                    } ,
                    {
                    pe_fixture_id = "dude-monster-run6-5", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -5, 12  ,  8, 11  ,  3, 16  ,  -5, 16  }
                    } ,
                    {
                    pe_fixture_id = "dude-monster-run6-5", density = 2, friction = 0, bounce = 0, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -7, -2  ,  -3, -7  ,  4, -8  ,  9, -4  ,  10, 3  ,  8, 5  ,  -6, 6  }
                    }
		}
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

